name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

categories:
  - title: '💥 Breaking Changes'
    label: 'breaking'

  - title: '🚀 Enhancements'
    label: 'enhancement'

  - title: '🐛 Bug Fixes'
    label: 'bug'

exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
  - 'github'

change-template: '* $TITLE ([#$NUMBER]($URL))'
template: |
  $CHANGES
